### ISSUE TITLE
Getting started with the library

### ISSUE THREAD

**Issue by FrankV01** [kdcllc/CometD.NetCore#1]
Your examples to setup salesforce are top notch. However, I've not seen any examples with the library itself. How do I create the object and register it to watch for streams/events/etc. (I'm new at this). 

I'll gladly help write documentation if you can point me in the right direction on this ticket...

**Comment by kdcllc** [comment]
@FrankV01 please refer to this library and `TestApp` https://github.com/kdcllc/CometD.NetCore.Salesforce/tree/master/src

**Comment by FrankV01** [comment]
This is fine, @kdcllc but if that is the answer I think the possible user-base of the library would be better served to have a small section in the readme to point folks to this example.
