### ISSUE TITLE
Should StateUpdateInProgressMutex really be a static Mutex?

### ISSUE THREAD

**Issue by AlexVallat** [kdcllc/CometD.NetCore#14]
It seems to me that this exclusion has no reason to synchronise across multiple instances of BayeuxClient, surely each should be independent? The `_stateUpdateInProgress` variable it protects is not static.

**Comment by AlexVallat** [comment]
(I only mention this because when debugging I sometimes get into a state where it throws AbandonedMutexException and never recovers from it, even when disposing and creating a new BayeuxClient.

**Comment by kdcllc** [comment]
@AlexVallat thanks for your contribution!
