### ISSUE TITLE
Several logging nuget packages are referenced, but are unused

### ISSUE THREAD

**Issue by AlexVallat** [kdcllc/CometD.NetCore#16]
There appears to be no use for the following nugets:

Microsoft.Extensions.Logging
Microsoft.Extensions.Logging.Configuration
Microsoft.Extensions.Logging.Console
Microsoft.Extensions.Logging.Debug

(The only one that actually is used is Microsoft.Extensions.Logging.Abstractions)

Can these be removed?

**Comment by kdcllc** [comment]
@AlexVallat removed and upgraded.
