### ISSUE TITLE
Add support for .Net LTS version (6.0)

### ISSUE THREAD

**Issue by tedvanderveen** [kdcllc/CometD.NetCore#30]
I notice this lib does not yet support .Net 6.0. Any plans on adding LTS version support? 
Are you open for a PR for that?

**Comment by kdcllc** [comment]
@tedvanderveen Yes, please create a PR for any changes you need to have!

**Comment by speed108** [comment]
Any updates about this?

**Comment by kdcllc** [comment]
@tedvanderveen  the latest release is using 7.0 now. I am closing this issue.
